# This workflow updates the lyncs-setuptools package on PyPI test if version is changed

name: lyncs-setuptools upload test

on:
  push:
    paths: 
      - 'extras/setuptools/lyncs_setuptools/version.py'

jobs:
  build-n-publish:  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.test_pypi_password }}
      run: |
        cd extras/setuptools
        python setup.py sdist bdist_wheel
        twine upload dist/*.tar.gz
